---Prod Validation

SELECT 
  MAX(
    LENGTH(COUNT_AS_NEW_DEAL)
  ) AS MAX_COUNT_AS_NEW_DEAL 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--5
SELECT 
  MAX(
    LENGTH(SOURCE_COMPANY)
  ) AS MAX_SOURCE_COMPANY 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--53
SELECT 
  MAX(
    LENGTH(COMPANY_ATTACHMENT_LEVERAGE)
  ) AS MAX_COMPANY_ATTACHMENT_LEVERAGE 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--4
SELECT 
  MAX(
    LENGTH(MIN_WAL)
  ) AS MAX_MIN_WAL 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--4
SELECT 
  MAX(
    LENGTH(MIN_IRR)
  ) AS MAX_MIN_IRR 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--6
SELECT 
  MAX(
    LENGTH(COMPANY_EBITDA)
  ) AS MAX_COMPANY_EBITDA 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--17
SELECT 
  MAX(
    LENGTH(ETL)
  ) AS MAX_ETL 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--5
SELECT 
  MAX(
    LENGTH(COLLATERAL_TYPE)
  ) AS MAX_COLLATERAL_TYPE 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--108
SELECT 
  MAX(
    LENGTH(COMPANY_TOTAL_LEVERAGE)
  ) AS MAX_COMPANY_TOTAL_LEVERAGE 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--4
SELECT 
  MAX(
    LENGTH(COMPANY_TOTAL_LTV)
  ) AS MAX_COMPANY_TOTAL_LTV 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--12
SELECT 
  MAX(
    LENGTH(CAP_CHARGE)
  ) AS MAX_CAP_CHARGE 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--6
SELECT 
  MAX(
    LENGTH(MIN_MOIC)
  ) AS MAX_MIN_MOIC 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--4
SELECT 
  MAX(
    LENGTH(COMPANY_EV_MULTIPLE)
  ) AS MAX_COMPANY_EV_MULTIPLE 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;
--4
SELECT 
  MAX(
    LENGTH(WEIGHTED_AVERAGE_LIFE)
  ) AS MAX_WEIGHTED_AVERAGE_LIFE 
FROM 
  PROD_STAGING.PUBLIC.DEALCLOUD_DAILY_DEALS;--4
