 SELECT 
      DISTINCT 
      b.full_date,
      b.aladdin_id,
      b.portfolio_code,
      b.pm_mandate, 
      b.pm_ibu,
      b.pm_lmg,
      
      --MARKET_VALUE--  
      coalesce(a.MARKET_VALUE_BASE,0)  AS MARKET_VALUE_BASE_UAT,
      coalesce(b.MARKET_VALUE_BASE,0)  AS MARKET_VALUE_BASE_PROD,
      ROUND(a.MARKET_VALUE_BASE - b.MARKET_VALUE_BASE, 10) AS MARKET_VALUE_BASE_DIFF,

      coalesce(a.MARKET_VALUE_LOCAL,0) AS MARKET_VALUE_LOCAL_UAT,
      coalesce(b.MARKET_VALUE_LOCAL,0) AS MARKET_VALUE_LOCAL_PROD,
      ROUND(a.MARKET_VALUE_LOCAL - b.MARKET_VALUE_LOCAL, 10) AS MARKET_VALUE_LOCAL_DIFF,

      coalesce(a.MARKET_VALUE_USD,0)   AS MARKET_VALUE_USD_UAT,
      coalesce(b.MARKET_VALUE_USD,0)   AS MARKET_VALUE_USD_PROD,
      ROUND(a.MARKET_VALUE_USD - b.MARKET_VALUE_USD, 10) AS MARKET_VALUE_USD_DIFF,

      --CLEAN_MARKET_VALUE--
      coalesce(a.CLEAN_MARKET_VALUE_BASE,0)  AS CLEAN_MARKET_VALUE_BASE_UAT,
      coalesce(b.CLEAN_MARKET_VALUE_BASE,0)  AS CLEAN_MARKET_VALUE_BASE_PROD,
      ROUND(a.CLEAN_MARKET_VALUE_BASE - b.CLEAN_MARKET_VALUE_BASE, 10) AS CLEAN_MARKET_VALUE_BASE_DIFF,

      coalesce(a.CLEAN_MARKET_VALUE_LOCAL,0) AS CLEAN_MARKET_VALUE_LOCAL_UAT,
      coalesce(b.CLEAN_MARKET_VALUE_LOCAL,0) AS CLEAN_MARKET_VALUE_LOCAL_PROD,
      ROUND(a.CLEAN_MARKET_VALUE_LOCAL - b.CLEAN_MARKET_VALUE_LOCAL, 10) AS CLEAN_MARKET_VALUE_LOCAL_DIFF,

      coalesce(a.CLEAN_MARKET_VALUE_USD,0)   AS CLEAN_MARKET_VALUE_USD_UAT,
      coalesce(b.CLEAN_MARKET_VALUE_USD,0)   AS CLEAN_MARKET_VALUE_USD_PROD,
      ROUND(a.CLEAN_MARKET_VALUE_USD - b.CLEAN_MARKET_VALUE_USD, 10) AS CLEAN_MARKET_VALUE_USD_DIFF,

      --SETTLEMENT_DATE_MARKET_VALUE--
      --NOTE: SETTLEMENT_DATE_MARKET_VALUE_LOCAL missing from CDSTS
      coalesce(a.SETTLEMENT_DATE_MARKET_VALUE_BASE,0)  AS SETTLEMENT_DATE_MARKET_VALUE_BASE_UAT,
      coalesce(b.SETTLEMENT_DATE_MARKET_VALUE_BASE,0)  AS SETTLEMENT_DATE_MARKET_VALUE_BASE_PROD,
      ROUND(a.SETTLEMENT_DATE_MARKET_VALUE_BASE - b.SETTLEMENT_DATE_MARKET_VALUE_BASE, 10) AS SETTLEMENT_DATE_MARKET_VALUE_BASE_DIFF,

      coalesce(a.SETTLEMENT_DATE_MARKET_VALUE_USD,0)   AS SETTLEMENT_DATE_MARKET_VALUE_USD_UAT,
      coalesce(b.SETTLEMENT_DATE_MARKET_VALUE_USD,0)   AS SETTLEMENT_DATE_MARKET_VALUE_USD_PROD,
      ROUND(a.SETTLEMENT_DATE_MARKET_VALUE_USD - b.SETTLEMENT_DATE_MARKET_VALUE_USD, 10) AS SETTLEMENT_DATE_MARKET_VALUE_USD_DIFF,

      --SETTLEMENT_DATE_CLEAN_MARKET_VALUE--
      coalesce(a.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE,0)  AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE_UAT,
      coalesce(b.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE,0)  AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE_PROD,
      ROUND(a.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE - b.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE, 10) AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_BASE_DIFF,

      coalesce(a.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL,0) AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL_UAT,
      coalesce(b.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL,0) AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL_PROD,
      ROUND(a.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL - b.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL, 10) AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_LOCAL_DIFF,

      coalesce(a.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD,0)   AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD_UAT,
      coalesce(b.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD,0)   AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD_PROD,
      ROUND(a.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD - b.SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD, 10) AS SETTLEMENT_DATE_CLEAN_MARKET_VALUE_USD_DIFF,

      --END_OF_DAY_MARKET_VALUE--
      --NOTE: END_OF_DAY_MARKET_VALUE_LOCAL missing from CDSTs
      coalesce(a.END_OF_DAY_MARKET_VALUE_BASE,0)  AS END_OF_DAY_MARKET_VALUE_BASE_UAT,
      coalesce(b.END_OF_DAY_MARKET_VALUE_BASE,0)  AS END_OF_DAY_MARKET_VALUE_BASE_PROD,
      ROUND(a.END_OF_DAY_MARKET_VALUE_BASE - b.END_OF_DAY_MARKET_VALUE_BASE, 10) AS END_OF_DAY_MARKET_VALUE_BASE_DIFF,

      coalesce(a.END_OF_DAY_MARKET_VALUE_USD,0) AS END_OF_DAY_MARKET_VALUE_USD_UAT,
      coalesce(b.END_OF_DAY_MARKET_VALUE_USD,0) AS END_OF_DAY_MARKET_VALUE_USD_PROD,
      ROUND(a.END_OF_DAY_MARKET_VALUE_USD - b.END_OF_DAY_MARKET_VALUE_USD, 10) AS END_OF_DAY_MARKET_VALUE_USD_DIFF,

      --SETTLEMENT_DATE_EXPOSURE--
      --NOTE: SETTLEMENT_DATE_EXPOSURE_LOCAL missing from CDSTs
      coalesce(a.SETTLEMENT_DATE_EXPOSURE_BASE,0)  AS SETTLEMENT_DATE_EXPOSURE_BASE_UAT,
      coalesce(b.SETTLEMENT_DATE_EXPOSURE_BASE,0) AS  SETTLEMENT_DATE_EXPOSURE_BASE_PROD,
      ROUND(a.SETTLEMENT_DATE_EXPOSURE_BASE - b.SETTLEMENT_DATE_EXPOSURE_BASE, 10) AS SETTLEMENT_DATE_EXPOSURE_BASE_DIFF,

      coalesce(a.SETTLEMENT_DATE_EXPOSURE_USD,0) ASSETTLEMENT_DATE_EXPOSURE_USD_UAT,
      coalesce(b.SETTLEMENT_DATE_EXPOSURE_USD,0) AS SETTLEMENT_DATE_EXPOSURE_USD_PROD,
      ROUND(a.SETTLEMENT_DATE_EXPOSURE_USD - b.SETTLEMENT_DATE_EXPOSURE_USD, 10) AS SETTLEMENT_DATE_EXPOSURE_USD_DIFF,

      --END_OF_DAY_EXPOSURE--
      --NOTE: END_OF_DAY_EXPOSURE_BASE_LOCAL missing from CDSTs
      coalesce(a.END_OF_DAY_EXPOSURE_BASE,0)  AS END_OF_DAY_EXPOSURE_BASE_UAT,
      coalesce(b.END_OF_DAY_EXPOSURE_BASE,0) AS  END_OF_DAY_EXPOSURE_BASE_PROD,
      ROUND(a.END_OF_DAY_EXPOSURE_BASE - b.END_OF_DAY_EXPOSURE_BASE, 10) AS END_OF_DAY_EXPOSURE_BASE_DIFF,

      coalesce(a.END_OF_DAY_EXPOSURE_USD,0) AS END_OF_DAY_EXPOSURE_USD_UAT,
      coalesce(b.END_OF_DAY_EXPOSURE_USD,0) AS END_OF_DAY_EXPOSURE_USD_PROD,
      ROUND(a.END_OF_DAY_EXPOSURE_USD - b.END_OF_DAY_EXPOSURE_USD, 10) AS END_OF_DAY_EXPOSURE_USD_DIFF,

      --EXPOSURE--
      coalesce(a.EXPOSURE_BASE,0)  AS EXPOSURE_BASE_UAT,
      coalesce(b.EXPOSURE_BASE,0)  AS EXPOSURE_BASE_PROD,
      ROUND(a.EXPOSURE_BASE - b.EXPOSURE_BASE, 10) AS EXPOSURE_BASE_DIFF,

      coalesce(a.EXPOSURE_LOCAL,0) AS EXPOSURE_LOCAL_UAT,
      coalesce(b.EXPOSURE_LOCAL,0) AS EXPOSURE_LOCAL_PROD,
      ROUND(a.EXPOSURE_LOCAL - b.EXPOSURE_LOCAL, 10) AS EXPOSURE_LOCAL_DIFF,

      coalesce(a.EXPOSURE_USD,0)   AS EXPOSURE_USD_UAT,
      coalesce(b.EXPOSURE_USD,0)   AS EXPOSURE_USD_PROD,
      ROUND(a.EXPOSURE_USD - b.EXPOSURE_USD, 10) AS EXPOSURE_USD_DIFF,

      --CURRENT_FACE--
      coalesce(a.CURRENT_FACE_BASE,0)  AS CURRENT_FACE_BASE_UAT,
      coalesce(b.CURRENT_FACE_BASE,0)  AS CURRENT_FACE_BASE_PROD,
      ROUND(a.CURRENT_FACE_BASE - b.CURRENT_FACE_BASE, 10) AS CURRENT_FACE_BASE_DIFF,

      coalesce(a.CURRENT_FACE_LOCAL,0) AS CURRENT_FACE_LOCAL_UAT,
      coalesce(b.CURRENT_FACE_LOCAL,0) AS CURRENT_FACE_LOCAL_PROD,
      ROUND(a.CURRENT_FACE_LOCAL - b.CURRENT_FACE_LOCAL, 10) AS CURRENT_FACE_LOCAL_DIFF,

      coalesce(a.CURRENT_FACE_USD,0)   AS CURRENT_FACE_USD_UAT,
      coalesce(b.CURRENT_FACE_USD,0)   AS CURRENT_FACE_USD_PROD,
      ROUND(a.CURRENT_FACE_USD - b.CURRENT_FACE_USD, 10) AS CURRENT_FACE_USD_DIFF,
      
      --UNFUNDED_BASE--  
      coalesce(a.UNFUNDED_BASE,0)  AS UNFUNDED_BASE_UAT,
      coalesce(b.UNFUNDED_BASE,0)  AS UNFUNDED_BASE_PROD,
      ROUND(a.UNFUNDED_BASE - b.UNFUNDED_BASE, 10) AS UNFUNDED_BASE_DIFF,

      coalesce(a.UNFUNDED_USD,0)  AS UNFUNDED_USD_UAT,
      coalesce(b.UNFUNDED_USD,0)  AS UNFUNDED_USD_PROD,
      ROUND(a.UNFUNDED_USD - b.UNFUNDED_USD, 10) AS UNFUNDED_USD_DIFF

  FROM SANDBOX_01.TEST_CAROLINE.CDST_IBOR_HOLDING_12_19_2025_BEFORE b
  left JOIN SANDBOX_01.TEST_CAROLINE.CDST_IBOR_HOLDING_12_19_2025_AFTER a
    ON a.full_date = b.full_date and a.asset_id = b.asset_id 
    and a.portfolio_id = b.portfolio_id
where b.full_date >= '2025-08-01'
and b.full_date <= '2025-12-19'
AND (
ABS(MARKET_VALUE_BASE_DIFF) > 1
OR ABS(MARKET_VALUE_USD_DIFF) > 1
OR ABS(MARKET_VALUE_LOCAL_DIFF) > 1
OR ABS(CLEAN_MARKET_VALUE_BASE_DIFF) > 1
OR ABS(CLEAN_MARKET_VALUE_USD_DIFF) > 1
OR ABS(CLEAN_MARKET_VALUE_LOCAL_DIFF) > 1
);