WITH before_nulls AS (
    SELECT DISTINCT
        ASSET_ID,
        ALADDIN_ID,
        CUSIP,
        LOANX_ID,
        DEAL_SPONSOR,
        LEAD_MANAGER,
        BASE_RATE,
        SPREAD,
        COUPON_RATE,
        ROW_EFFECTIVE_DATE,
        ROW_EXPIRATION_DATE
    FROM SANDBOX_01.TEST_CAROLINE.DIM_ASSET_02_23_2026_BEFORE
    WHERE (DEAL_SPONSOR IS NULL OR TRIM(DEAL_SPONSOR) = '')
       OR (LEAD_MANAGER  IS NULL OR TRIM(LEAD_MANAGER)  = '')
    AND ROW_EFFECTIVE_DATE between ROW_EFFECTIVE_DATE and ROW_EXPIRATION_DATE
),
after_nulls AS (
    SELECT DISTINCT
        ASSET_ID,
        ALADDIN_ID,
        CUSIP,
        LOANX_ID,
        DEAL_SPONSOR,
        LEAD_MANAGER,
        BASE_RATE,
        SPREAD,
        COUPON_RATE,
        ROW_EFFECTIVE_DATE,
        ROW_EXPIRATION_DATE
    FROM SANDBOX_01.TEST_CAROLINE.DIM_ASSET_02_24_2026_AFTER
    WHERE (DEAL_SPONSOR IS NULL OR TRIM(DEAL_SPONSOR) = '')
       OR (LEAD_MANAGER  IS NULL OR TRIM(LEAD_MANAGER)  = '')
        AND ROW_EFFECTIVE_DATE between ROW_EFFECTIVE_DATE and ROW_EXPIRATION_DATE
)
SELECT DISTINCT
    b.ASSET_ID,
    b.ALADDIN_ID,
    b.CUSIP,
    b.LOANX_ID,
    b.DEAL_SPONSOR  AS BEFORE_DEAL_SPONSOR,
    a.DEAL_SPONSOR  AS AFTER_DEAL_SPONSOR,
    b.LEAD_MANAGER  AS BEFORE_LEAD_MANAGER,
    a.LEAD_MANAGER  AS AFTER_LEAD_MANAGER,
    b.BASE_RATE     AS BEFORE_BASE_RATE,
    a.BASE_RATE     AS AFTER_BASE_RATE,
    b.SPREAD        AS BEFORE_SPREAD,
    a.SPREAD        AS AFTER_SPREAD,
    b.COUPON_RATE   AS BEFORE_COUPON_RATE,
    a.COUPON_RATE   AS AFTER_COUPON_RATE,
    b.ROW_EFFECTIVE_DATE,
    a.ROW_EFFECTIVE_DATE,
    a.ROW_EXPIRATION_DATE
FROM before_nulls b
JOIN after_nulls a
  ON  b.ASSET_ID   = a.ASSET_ID
WHERE b.ROW_EFFECTIVE_DATE BETWEEN a.ROW_EFFECTIVE_DATE AND a.ROW_EXPIRATION_DATE
AND  (NVL(b.DEAL_SPONSOR, '') <> NVL(a.DEAL_SPONSOR, '')
   OR NVL(b.LEAD_MANAGER, '') <> NVL(a.LEAD_MANAGER, ''))
   and NVL(a.DEAL_SPONSOR, '') = ''
   and NVL(a.LEAD_MANAGER, '') = ''
ORDER BY ASSET_ID, ALADDIN_ID, CUSIP, LOANX_ID;




WITH WSO_LOANX_ID AS (
SELECT DISTINCT 
    wsoe.business_date,
    edm.aladdin_id,
    wsoe.lead_manager,
    wsoe.deal_sponsor,
    AVG(CASE WHEN TRIM(CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN CONTRACT_BASE_RATE END) CONTRACT_BASE_RATE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN (wsoe.CONTRACT_SPREADADJUSTMENT + wsoe.CONTRACT_SPREAD) END) CONTRACT_SPREAD,
    MAX(CASE WHEN TRIM(CONTRACT_NAME) IN ('UNFND','Unfunded') 
        THEN COMMITMENT_FEE END) COMMITMENT_FEE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN (wsoe.WEIGHTED_AVERAGE_ALL_IN_RATE*100) END) COUPON_RATE,
        wsoe.loanx_id as wsoe_id
FROM PROD_STAGING.PUBLIC.WSO_DAILY_SECURITYMASTER_ENRICHMENT wsoe
INNER JOIN PROD_STAGING.PUBLIC.EDM_DAILY_SECURITYMASTER edm
   ON WSOE.LOANX_ID = EDM.LOANX_ID
   AND COALESCE(WSOE.LOANX_ID,'') <> ''
   AND WSOE.BUSINESS_DATE = EDM.BUSINESS_DATE
GROUP BY 1,2,3,4,9
),

WSO_SECURITY_ID AS (
SELECT DISTINCT 
    wsoe.business_date,
    edm.aladdin_id,
    wsoe.lead_manager,
    wsoe.deal_sponsor,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN wsoe.CONTRACT_BASE_RATE END) CONTRACT_BASE_RATE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN (wsoe.CONTRACT_SPREADADJUSTMENT + wsoe.CONTRACT_SPREAD) END) CONTRACT_SPREAD,
    MAX(CASE WHEN TRIM(wsoe.CONTRACT_NAME) IN ('UNFND','Unfunded') 
        THEN wsoe.COMMITMENT_FEE END) COMMITMENT_FEE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN (wsoe.WEIGHTED_AVERAGE_ALL_IN_RATE*100) END) COUPON_RATE,
        wsoe.security_id as wsoe_id
FROM PROD_STAGING.PUBLIC.WSO_DAILY_SECURITYMASTER_ENRICHMENT WSOE
INNER JOIN PROD_STAGING.PUBLIC.EDM_DAILY_SECURITYMASTER EDM
   ON WSOE.SECURITY_ID = EDM.LIN
   AND COALESCE(SECURITY_ID,'') <> ''
   AND WSOE.BUSINESS_DATE = EDM.BUSINESS_DATE
WHERE
   NOT EXISTS (SELECT 1 FROM WSO_LOANX_ID LNX WHERE EDM.ALADDIN_ID = LNX.ALADDIN_ID)
GROUP BY 1,2,3,4,9
),

WSO_CUSIP_ID AS (
SELECT DISTINCT 
    wsoe.business_date,
    edm.aladdin_id,
    wsoe.lead_manager,
    wsoe.deal_sponsor,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN wsoe.CONTRACT_BASE_RATE END) CONTRACT_BASE_RATE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN (wsoe.CONTRACT_SPREADADJUSTMENT + wsoe.CONTRACT_SPREAD) END) CONTRACT_SPREAD,
    MAX(CASE WHEN TRIM(wsoe.CONTRACT_NAME) IN ('UNFND','Unfunded') 
        THEN wsoe.COMMITMENT_FEE END) COMMITMENT_FEE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded') 
        THEN (wsoe.WEIGHTED_AVERAGE_ALL_IN_RATE*100) END) COUPON_RATE,
        wsoe.security_id as wsoe_id
FROM PROD_STAGING.PUBLIC.WSO_DAILY_SECURITYMASTER_ENRICHMENT WSOE
INNER JOIN PROD_STAGING.PUBLIC.EDM_DAILY_SECURITYMASTER EDM
   ON WSOE.CUSIP_ID = EDM.ALADDIN_ID
   AND COALESCE(WSOE.CUSIP_ID,'') <> ''
   AND WSOE.BUSINESS_DATE = EDM.BUSINESS_DATE
WHERE
   NOT EXISTS (SELECT 1 FROM WSO_LOANX_ID LNX WHERE EDM.ALADDIN_ID = LNX.ALADDIN_ID)
   AND NOT EXISTS (SELECT 1 FROM WSO_SECURITY_ID SEC WHERE EDM.ALADDIN_ID = SEC.ALADDIN_ID)
GROUP BY 1,2,3,4,9
)
