WITH dedup_before AS (
    SELECT *
    FROM SANDBOX_01.TEST_CAROLINE.CDST_IBOR_HOLDING_12_19_2025_BEFORE
    WHERE full_date BETWEEN '2025-08-01' AND '2025-12-19'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY full_date, asset_id, portfolio_id
        ORDER BY full_date
    ) = 1
),
dedup_after AS (
    SELECT *
    FROM SANDBOX_01.TEST_CAROLINE.CDST_IBOR_HOLDING_12_19_2025_AFTER
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY full_date, asset_id, portfolio_id
        ORDER BY full_date
    ) = 1
),
base_compare AS (
    SELECT
        b.full_date,
        b.aladdin_id,
        b.portfolio_code,
        b.pm_mandate,
        b.pm_ibu,
        b.pm_lmg,

        /* MARKET VALUE */
        ROUND(COALESCE(a.MARKET_VALUE_BASE,0) - COALESCE(b.MARKET_VALUE_BASE,0),10) AS MARKET_VALUE_BASE_DIFF,
        ROUND(COALESCE(a.MARKET_VALUE_LOCAL,0) - COALESCE(b.MARKET_VALUE_LOCAL,0),10) AS MARKET_VALUE_LOCAL_DIFF,
        ROUND(COALESCE(a.MARKET_VALUE_USD,0)   - COALESCE(b.MARKET_VALUE_USD,0),10)   AS MARKET_VALUE_USD_DIFF,

        /* CLEAN MARKET VALUE */
        ROUND(COALESCE(a.CLEAN_MARKET_VALUE_BASE,0)  - COALESCE(b.CLEAN_MARKET_VALUE_BASE,0),10)  AS CLEAN_MARKET_VALUE_BASE_DIFF,
        ROUND(COALESCE(a.CLEAN_MARKET_VALUE_LOCAL,0) - COALESCE(b.CLEAN_MARKET_VALUE_LOCAL,0),10) AS CLEAN_MARKET_VALUE_LOCAL_DIFF,
        ROUND(COALESCE(a.CLEAN_MARKET_VALUE_USD,0)   - COALESCE(b.CLEAN_MARKET_VALUE_USD,0),10)   AS CLEAN_MARKET_VALUE_USD_DIFF,

        /* EXPOSURE */
        ROUND(COALESCE(a.EXPOSURE_BASE,0)  - COALESCE(b.EXPOSURE_BASE,0),10)  AS EXPOSURE_BASE_DIFF,
        ROUND(COALESCE(a.EXPOSURE_LOCAL,0) - COALESCE(b.EXPOSURE_LOCAL,0),10) AS EXPOSURE_LOCAL_DIFF,
        ROUND(COALESCE(a.EXPOSURE_USD,0)   - COALESCE(b.EXPOSURE_USD,0),10)   AS EXPOSURE_USD_DIFF,

        /* CURRENT FACE */
        ROUND(COALESCE(a.CURRENT_FACE_BASE,0)  - COALESCE(b.CURRENT_FACE_BASE,0),10)  AS CURRENT_FACE_BASE_DIFF,
        ROUND(COALESCE(a.CURRENT_FACE_LOCAL,0) - COALESCE(b.CURRENT_FACE_LOCAL,0),10) AS CURRENT_FACE_LOCAL_DIFF,
        ROUND(COALESCE(a.CURRENT_FACE_USD,0)   - COALESCE(b.CURRENT_FACE_USD,0),10)   AS CURRENT_FACE_USD_DIFF,

        /* UNFUNDED */
        ROUND(COALESCE(a.UNFUNDED_BASE,0) - COALESCE(b.UNFUNDED_BASE,0),10) AS UNFUNDED_BASE_DIFF,
        ROUND(COALESCE(a.UNFUNDED_USD,0)  - COALESCE(b.UNFUNDED_USD,0),10)  AS UNFUNDED_USD_DIFF

    FROM dedup_before b
    LEFT JOIN dedup_after a
        ON a.full_date = b.full_date
       AND a.asset_id = b.asset_id
       AND a.portfolio_id = b.portfolio_id
)
