
/*We want to keep our current logic that only uses funded contracts (CONTRACT_NAME that are not 'UNFND','Unfunded') when we calculate things like base rate, spread, and coupon. In addition to that, we also need to include loans where all the CONTRACT_NAME are null , so those loans are no longer dropped from the view.we are excluding about 18–20 loans because both the lead manager and deal sponsor are null for those loans because of current filter logic in where condition and also We need to change the logic using case or iff or decode or something more efficient solution so those loans are included in the view, even if the lead manager and deal sponsor are null.*/

WITH WSO_LOANX_ID AS (
SELECT DISTINCT
    wsoe.business_date,
    edm.aladdin_id,
    wsoe.lead_manager,
    wsoe.deal_sponsor,
    AVG(CASE WHEN TRIM(CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN CONTRACT_BASE_RATE END) CONTRACT_BASE_RATE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN (wsoe.CONTRACT_SPREADADJUSTMENT + wsoe.CONTRACT_SPREAD) END) CONTRACT_SPREAD,
    MAX(CASE WHEN TRIM(CONTRACT_NAME) IN ('UNFND','Unfunded')
        THEN COMMITMENT_FEE END) COMMITMENT_FEE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN (wsoe.WEIGHTED_AVERAGE_ALL_IN_RATE*100) END) COUPON_RATE
FROM PROD_STAGING.PUBLIC.WSO_DAILY_SECURITYMASTER_ENRICHMENT wsoe
INNER JOIN PROD_STAGING.PUBLIC.EDM_DAILY_SECURITYMASTER edm
   ON WSOE.LOANX_ID = EDM.LOANX_ID
   AND COALESCE(WSOE.LOANX_ID,'') <> ''
   AND WSOE.BUSINESS_DATE = EDM.BUSINESS_DATE
WHERE
   (WSOE.LEAD_MANAGER <> '' OR WSOE.DEAL_SPONSOR <> '')
   AND (WSOE.LEAD_MANAGER IS NOT NULL OR WSOE.DEAL_SPONSOR IS NOT NULL)
GROUP BY 1,2,3,4
),

WSO_SECURITY_ID AS (
SELECT DISTINCT
    wsoe.business_date,
    edm.aladdin_id,
    wsoe.lead_manager,
    wsoe.deal_sponsor,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN wsoe.CONTRACT_BASE_RATE END) CONTRACT_BASE_RATE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN (wsoe.CONTRACT_SPREADADJUSTMENT + wsoe.CONTRACT_SPREAD) END) CONTRACT_SPREAD,
    MAX(CASE WHEN TRIM(wsoe.CONTRACT_NAME) IN ('UNFND','Unfunded')
        THEN wsoe.COMMITMENT_FEE END) COMMITMENT_FEE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN (wsoe.WEIGHTED_AVERAGE_ALL_IN_RATE*100) END) COUPON_RATE
FROM PROD_STAGING.PUBLIC.WSO_DAILY_SECURITYMASTER_ENRICHMENT WSOE
INNER JOIN PROD_STAGING.PUBLIC.EDM_DAILY_SECURITYMASTER EDM
   ON WSOE.SECURITY_ID = EDM.LIN
   AND COALESCE(SECURITY_ID,'') <> ''
   AND WSOE.BUSINESS_DATE = EDM.BUSINESS_DATE
WHERE
   NOT EXISTS (SELECT 1 FROM WSO_LOANX_ID LNX WHERE EDM.ALADDIN_ID = LNX.ALADDIN_ID)
   AND (WSOE.LEAD_MANAGER <> '' OR WSOE.DEAL_SPONSOR <> '')
   AND (WSOE.LEAD_MANAGER IS NOT NULL OR WSOE.DEAL_SPONSOR IS NOT NULL)
GROUP BY 1,2,3,4
),

WSO_CUSIP_ID AS (
SELECT DISTINCT
    wsoe.business_date,
    edm.aladdin_id,
    wsoe.lead_manager,
    wsoe.deal_sponsor,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN wsoe.CONTRACT_BASE_RATE END) CONTRACT_BASE_RATE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN (wsoe.CONTRACT_SPREADADJUSTMENT + wsoe.CONTRACT_SPREAD) END) CONTRACT_SPREAD,
    MAX(CASE WHEN TRIM(wsoe.CONTRACT_NAME) IN ('UNFND','Unfunded')
        THEN wsoe.COMMITMENT_FEE END) COMMITMENT_FEE,
    AVG(CASE WHEN TRIM(wsoe.CONTRACT_NAME) NOT IN ('UNFND','Unfunded')
        THEN (wsoe.WEIGHTED_AVERAGE_ALL_IN_RATE*100) END) COUPON_RATE
FROM PROD_STAGING.PUBLIC.WSO_DAILY_SECURITYMASTER_ENRICHMENT WSOE
INNER JOIN PROD_STAGING.PUBLIC.EDM_DAILY_SECURITYMASTER EDM
   ON WSOE.CUSIP_ID = EDM.ALADDIN_ID
   AND COALESCE(WSOE.CUSIP_ID,'') <> ''
   AND WSOE.BUSINESS_DATE = EDM.BUSINESS_DATE
WHERE
   NOT EXISTS (SELECT 1 FROM WSO_LOANX_ID LNX WHERE EDM.ALADDIN_ID = LNX.ALADDIN_ID)
   AND NOT EXISTS (SELECT 1 FROM WSO_SECURITY_ID SEC WHERE EDM.ALADDIN_ID = SEC.ALADDIN_ID)
   AND (WSOE.LEAD_MANAGER <> '' OR WSOE.DEAL_SPONSOR <> '')
   AND (WSOE.LEAD_MANAGER IS NOT NULL OR WSOE.DEAL_SPONSOR IS NOT NULL)
GROUP BY 1,2,3,4
)
